import esbuild from "esbuild";
import { readFileSync } from "node:fs";

const banner = {
  js: `/*
  INSIGHTS – SUBCONSCIOUS AI
  Build file generated by esbuild
*/`,
};

/** @type {import('esbuild').BuildOptions} */
const baseConfig = {
  entryPoints: ["main.ts"],
  bundle: true,
  outfile: "main.js",
  target: ["es2020"],
  platform: "browser",
  format: "cjs",
  sourcemap: process.argv.includes("--watch") ? "inline" : false,
  external: ["obsidian"],
  banner,
};

async function build() {
  const ctx = await esbuild.context(baseConfig);
  if (process.argv.includes("--watch")) {
    await ctx.watch();
    console.log("[esbuild] watching for changes...");
  } else {
    await ctx.rebuild();
    await ctx.dispose();
    console.log("[esbuild] build complete");
  }
}

build().catch((err) => {
  console.error(err);
  process.exit(1);
});